services:
  db:
    container_name: borea_db
    environment:
      POSTGRES_DB: borea
      POSTGRES_PASSWORD: borea
      POSTGRES_USER: borea
    image: postgres:alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    container_name: borea_redis
    image: redis:alpine
  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    container_name: borea_web
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://borea:borea@db:5432/borea
      IS_DOCKER: 'true'
      REDIS_URL: redis://redis:6379/
      SECRET_KEY: '<randomly generated secret key>'
    links:
      - db:db
      - redis:redis
    ports:
      - 8000:8000
      - 80:8000
volumes:
  postgres-data:
